routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::middleware(['auth', 'isAdmin'])->group(function () {
    Route::get('/admin', [App\Http\Controllers\HomeController::class, 'index'])->name('adminHome');
    Route::resource('/admin/brand', 'App\Http\Controllers\BrandController');
    Route::resource('/admin/model', 'App\Http\Controllers\AutomobileModelController');
    Route::resource('/admin/car', 'App\Http\Controllers\AutomobileController');
    Route::resource('/admin/color', 'App\Http\Controllers\ColorController');
});

Auth::routes();

app/Models/Automobile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Facades\Storage;

class Automobile extends Model
{
    use HasFactory;

    public $timestamps = false;

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 10;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'model_id',
        'color_id',
        'photo',
        'year_manufacture',
        'license_plate',
        'rental_price',
        'transmission'
    ];

    public function model(): BelongsTo
    {
        return $this->belongsTo(AutomobileModel::class, 'model_id');
    }

    public function color(): HasOne
    {
        return $this->HasOne(Color::class, 'id', 'color_id');
    }

    /**
     * Get the car's name.
     *
     * @return string
     */
    public function getCarNameAttribute(): string
    {
        return "{$this->model->brand->name} {$this->model->name}";
    }

    /**
     * The method deletes a previously uploaded photo
     *
     */
    public function deleteImage(): bool
    {
        if (Storage::disk('public')->exists($this->photo)){
            return Storage::disk('public')->delete($this->photo);
        }
        return true;
    }

}

app/Http/Controllers/AutomobileController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Enum;
use App\Http\Requests\StoreAutomobileRequest;
use App\Http\Requests\UpdateAutomobileRequest;
use App\Models\Automobile;
use App\Models\AutomobileModel;
use App\Models\Brand;
use App\Models\Color;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Database\QueryException;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Storage;

class AutomobileController extends Controller
{
    /**
     * @var string
     */
    private $title = "Cars";

    /**
     * @var string
     */
    private $pageName = "";

    /**
     * Display a listing of the resource.
     *
     * @return Renderable ;
     */
    public function index(): Renderable
    {
        return view('admin/automobile/index', [
            'title' => $this->title,
            'cars' => Automobile::paginate()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Renderable
     */
    public function create(): Renderable
    {
        $this->pageName = "Create car";

        return view('admin/automobile/create', [
            'title' => $this->title,
            'pageName' => $this->pageName,
            'data' => [
                'brands' => Brand::all(),
                'models' => AutomobileModel::all(),
                'transmissions' => Enum::getEnumValues('automobiles', 'transmission'),
                'colors' => Color::all(),
                'car' => null
            ]
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreAutomobileRequest $request
     * @return RedirectResponse
     */
    public function store(StoreAutomobileRequest $request): RedirectResponse
    {
        if ($request->hasFile('car_photo')){
            $request->merge([
                'photo' => Storage::disk('public')->put('photo', $request->file('car_photo'))
            ]);
        }

        try {
            Automobile::create($request->except('car_photo'));
        } catch (QueryException $error) {
            return redirect()->back()
                ->withErrors(['error' => $error->getMessage()])
                ->withInput($request->input());
        }

        return redirect()->route('car.index')
                ->with('success','Car created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param Automobile $car
     * @return Renderable
     */
    public function show(Automobile $car): Renderable
    {
        $this->pageName = "View car \"" . $car->car_name . "\"";

        return view('admin.automobile.show', [
            'title' => $this->title,
            'pageName' => $this->pageName,
            'car' => $car
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Automobile $car
     * @return Renderable
     */
    public function edit(Automobile $car): Renderable
    {
        $this->pageName = "Edit car \"" . $car->car_name . "\"";

        return view('admin.automobile.edit', [
            'title' => 'Edit brand',
            'pageName' => $this->pageName,
            'data' => [
                'brands' => Brand::all(),
                'models' => AutomobileModel::all(),
                'transmissions' => Enum::getEnumValues('automobiles', 'transmission'),
                'colors' => Color::all(),
                'car' => $car]
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateAutomobileRequest $request
     * @param Automobile $car
     * @return RedirectResponse
     */
    public function update(UpdateAutomobileRequest $request, Automobile $car): RedirectResponse
    {
        if ($request->hasFile('car_photo')){
            $car->deleteImage();
            $request->merge([
                'photo' => Storage::disk('public')->put('photo', $request->file('car_photo'))
            ]);
        }

        try {
            $car->update($request->except('car_photo'));
        } catch (QueryException $error) {
            return redirect()->back()
                ->withErrors(['error' => $error->getMessage()])
                ->withInput($request->input());
        }

        return redirect()->route('car.index')
                ->with('success','Car updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Automobile $car
     * @return RedirectResponse
     */
    public function destroy(Automobile $car): RedirectResponse
    {
        try {
            $car->delete();
            $car->deleteImage();
        } catch (QueryException $error) {
            return redirect()->back()
                ->withErrors(['error' => $error->getMessage()]);
        }

        return redirect()->route('car.index')
                ->with('success','Car deleted successfully.');
    }
}

resources/views/admin/automobile/_form.blade.php
<div class="card card-default">
    <form action="{{ $route }}" method="POST" enctype="multipart/form-data">
        @csrf
        @if($method)
            @method($method)
        @endif
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="model_id">Model name</label>
                        <select class="custom-select form-control-border" id="model_id" name="model_id"
                                autocomplete="off">
                            <option value="0">
                                Select model
                            </option>
                            @foreach($data['models'] AS $model)
                                <option value="{{ $model->id }}"
                                @if($data['car'])
                                    {{ ($model->id == $data['car']->model_id) ? 'selected=selected' : '' }}
                                    @else
                                    {{ ($model->id == old('model_id')) ? 'selected=selected' : '' }}
                                    @endif
                                >
                                    {{ $model->brand->name . " " . $model->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="transmission">Transmission</label>
                        <select class="custom-select form-control-border" id="transmission" name="transmission"
                                autocomplete="off">
                            <option value="0">
                                Select transmission
                            </option>
                            @foreach($data['transmissions'] AS $transmission)
                                <option value="{{ $transmission }}"
                                @if($data['car'])
                                    {{ ($transmission == $data['car']->transmission) ? 'selected=selected' : '' }}
                                    @else
                                    {{ ($transmission == old('transmission')) ? 'selected=selected' : '' }}
                                    @endif
                                >
                                    {{ $transmission }}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="colorId">Color</label>
                        <select class="custom-select form-control-border" id="colorId" name="color_id"
                                autocomplete="off">
                            <option value="0">
                                Select color
                            </option>
                            @foreach($data['colors'] AS $color)
                                <option value="{{ $color->id }}"
                                @if($data['car'])
                                    {{ ($color->id == $data['car']->color_id) ? 'selected=selected' : '' }}
                                @else
                                    {{ ($color->id == old('color_id')) ? 'selected=selected' : '' }}
                                @endif
                                >
                                    {{ $color->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="yearManufacture">Year of manufacture</label>
                        <input type="text" class="form-control" id="yearManufacture" name="year_manufacture"
                               placeholder="Enter year of manufacture"
                               value="{{ $data['car'] ? $data['car']->year_manufacture : old('year_manufacture') }}"
                        >
                    </div>

                    <div class="form-group">
                        <label for="licensePlate">License plate</label>
                        <input type="text" class="form-control" id="licensePlate" name="license_plate"
                               placeholder="Enter license plate"
                               value="{{ $data['car'] ? $data['car']->license_plate : old('license_plate') }}"
                        >
                    </div>

                    <div class="form-group">
                        <label for="rentalPrice">Rental price</label>
                        <input type="text" class="form-control" id="rentalPrice" name="rental_price"
                               placeholder="Enter rental price"
                               value="{{ $data['car'] ? $data['car']->rental_price : old('rental_price') }}"
                        >
                    </div>
                </div>

                <div class="col-sm-6">
                    @if (isset($data['car']))
                        @if (\Illuminate\Support\Facades\Storage::disk('public')->exists($data['car']->photo))
                            <a type="button" class="modal-image-trigger" data-toggle="modal"
                               data-target="#modal_image"
                               data-image-url="{{ url(\Illuminate\Support\Facades\Storage::url($data['car']->photo)) }}"
                               data-image-alt="{{ $data['car']->model->brand->name }} {{ $data['car']->model->name }}"
                            >
                                <img class="img-fluid"
                                     style="width: 380px;"
                                     src="{{ url(\Illuminate\Support\Facades\Storage::url($data['car']->photo)) }}"
                                     alt="{{ $data['car']->model->brand->name }} {{ $data['car']->model->name }}">
                            </a>

                        @else
                            <img class="img-fluid"
                                 src="https://via.placeholder.com/380.png?text={{ $data['car']->model->brand->name }} {{ $data['car']->model->name }}"
                                 alt="{{ $data['car']->model->brand->name }} {{ $data['car']->model->name }}"/>
                        @endif
                    @else
                        <img class="img-fluid"
                             src="https://via.placeholder.com/380.png?text=Upload car photo"
                             alt="Upload car photo"/>
                    @endif
                    <div class="form-group">
                        <label for="car_photo">Automobile photo (max size - 1Mb)</label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="car_photo" name="car_photo">
                                <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                            </div>
                            <div class="input-group-append">
                                <span class="input-group-text">Upload</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>
</div>
@include('admin.includes.image-modal')

resources/views/admin/automobile/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        @include('admin.includes.headerWithBreadcrumbs', [
            'route' => route('brand.index'),
            'title' => $title,
            'pageName' => $pageName ?? null
        ])
    </section>
    <section class="content">
        @if ($errors->any())
            @include('admin.includes.errors', ['errors' => $errors])
        @endif

        @include('admin/automobile/_form', [
            'route' => route('car.store'),
            'method' => null,
            'errors' => $errors,
            'data' => $data
        ])
    </section>
@endsection

resources/views/admin/automobile/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        @include('admin.includes.headerWithBreadcrumbs', [
            'route' => route('model.index'),
            'title' => $title,
            'pageName' => $pageName ?? null
        ])
    </section>
    <section class="content">
        @if ($errors->any())
            @include('admin.includes.errors', ['errors' => $errors])
        @endif

        @include('admin/automobile/_form', [
            'route' => route('car.update', $data['car']->id),
            'method' => 'PUT',
            'errors' => $errors,
            'data' => $data
        ])
    </section>
@endsection

resources/views/admin/automobile/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        @include('admin.includes.headerWithBreadcrumbs', [
            'route' => route('brand.index'),
            'title' => $title,
            'pageName' => $pageName ?? null
        ])
    </section>

    <section class="content">
        @if(session()->has('success'))
            @include('admin.includes.success')
        @endif
        <div class="card">
            <div class="card-header">
                <a class="btn btn-success btn-sm mw-100" href="{{ route('car.create') }}">
                    <i class="far fa-plus-square"></i>
                </a>
                <div class="card-tools">
                    {{ $cars->links() }}
                </div>
            </div>
            @if ($cars->isNotEmpty())
                <div class="card-body p-0" style="display: block;">
                <table class="table table-striped projects">
                    <thead>
                    <tr>
                        <th style="width: 1%">#</th>
                        <th style="width: 5%">Photo</th>
                        <th style="width: 10%">Brand name</th>
                        <th style="width: 10%">Model Name</th>
                        <th style="width: 10%">Year</th>
                        <th style="width: 10%">License plate</th>
                        <th style="width: 10%">Color</th>
                        <th style="width: 10%">Transmission</th>
                        <th style="width: 10%">Rental price</th>
                        <th style="width: 5%">{{-- --}}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($cars AS $car)
                    <tr>
                        <td>
                            {{ $car->id }}
                        </td>
                        <td>
                            <a href="{{ route('car.show', $car->id) }}">
                                @if (\Illuminate\Support\Facades\Storage::disk('public')->exists($car->photo))
                                    <img class="img-fluid"
                                         src="{{ url(\Illuminate\Support\Facades\Storage::url($car->photo)) }}"
                                         alt="{{ $car->model->brand->name }} {{ $car->model->name }}">
                                @else
                                    <img class="img-fluid"
                                         src="https://via.placeholder.com/120.png?text={{ $car->model->brand->name }} {{ $car->model->name }}"
                                         alt="{{ $car->model->brand->name }} {{ $car->model->name }}"/>
                                @endif
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('car.show', $car->id) }}">
                                {{ $car->model->brand->name }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('car.show', $car->id) }}">
                                {{ $car->model->name }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('car.show', $car->id) }}">
                                {{ $car->year_manufacture }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('car.show', $car->id) }}">
                                {{ \Illuminate\Support\Str::upper($car->license_plate) }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('car.show', $car->id) }}">
                                {{ $car->color->name }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('car.show', $car->id) }}">
                                {{ $car->transmission }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('car.show', $car->id) }}">
                                {{ $car->rental_price }}
                            </a>
                        </td>
                        <td class="project-actions text-right">
                            <div class="btn-group">
                                <a class="btn btn-outline-primary btn-sm" href="{{ route('car.edit', $car->id) }}">
                                    <i class="fas fa-pencil-alt pt-2 pl-1 pr-1"></i>
                                </a>
                                <a type="button" class="btn btn-outline-danger delete-trigger" data-toggle="modal"
                                   data-target="#modal_delete"
                                   data-delete-url="{{ route('car.destroy', $car->id) }}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
                </div>
            @else
                <div class="card-body" style="display: block;">
                    <div class="col-12">
                        <h5>{{ __('messages.cars.noDataFound') }}</h5>
                    </div>
                </div>
            @endif
            <div class="card-footer clearfix">
                {{ $cars->links() }}
            </div>
        </div>
    </section>
    @include('admin.includes.delete-modal',[
            'message' => __('messages.cars.onDeleteRecord')
        ])
@endsection

resources/views/admin/automobile/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        @include('admin.includes.headerWithBreadcrumbs', [
            'route' => route('car.index'),
            'title' => $title,
            'pageName' => $pageName ?? null
        ])
    </section>
    <section class="content">
        <div class="card">
            <div class="card-header">
                <a class="btn btn-success btn-sm mw-100" href="{{ route('car.edit', $car->id) }}">
                    <i class="fas fa-pencil-alt"></i>
                </a>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Model name</label>
                            <p>{{ $car->model->brand->name . " " . $car->model->name }}</p>
                        </div>

                        <div class="form-group">
                            <label>Transmission</label>
                            <p>{{ $car->transmission }}</p>
                        </div>

                        <div class="form-group">
                            <label>Color</label>
                            <p>{{ $car->color->name }}</p>
                        </div>

                        <div class="form-group">
                            <label>Year of manufacture</label>
                            <p>{{ $car->year_manufacture }}</p>
                        </div>

                        <div class="form-group">
                            <label>License plate</label>
                            <p>{{ \Illuminate\Support\Str::upper($car->license_plate) }}</p>
                        </div>

                        <div class="form-group">
                            <label>Rental price</label>
                            <p>{{ $car->rental_price }}</p>
                        </div>
                    </div>

                    <div class="col-sm-6">
                        @if (\Illuminate\Support\Facades\Storage::disk('public')->exists($car->photo))
                            <a type="button" class="modal-image-trigger" data-toggle="modal"
                               data-target="#modal_image"
                               data-image-url="{{ url(\Illuminate\Support\Facades\Storage::url($car->photo)) }}"
                               data-image-alt="{{ $car->model->brand->name }} {{ $car->model->name }}"
                            >
                                <img class="img-fluid"
                                     style="width: 380px;"
                                     src="{{ url(\Illuminate\Support\Facades\Storage::url($car->photo)) }}"
                                     alt="{{ $car->model->brand->name }} {{ $car->model->name }}">
                            </a>
                        @else
                            <img class="img-fluid"
                                 src="https://via.placeholder.com/380.png?text={{ $car->model->brand->name }} {{ $car->model->name }}"
                                 alt="{{ $car->model->brand->name }} {{ $car->model->name }}"/>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </section>
    @include('admin.includes.image-modal')
@endsection