routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::middleware(['auth', 'isAdmin'])->group(function () {
    Route::get('/admin', [App\Http\Controllers\HomeController::class, 'index'])->name('adminHome');
    Route::resource('/admin/brand', 'App\Http\Controllers\BrandController');
    Route::resource('/admin/model', 'App\Http\Controllers\AutomobileModelController');
    Route::resource('/admin/car', 'App\Http\Controllers\AutomobileController');
    Route::resource('/admin/color', 'App\Http\Controllers\ColorController');
});

Auth::routes();

app/Models/Automobile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Facades\Storage;

class Automobile extends Model
{
    use HasFactory;

    public $timestamps = false;

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 10;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'model_id',
        'color_id',
        'photo',
        'year_manufacture',
        'license_plate',
        'rental_price',
        'transmission'
    ];

    public function model(): BelongsTo
    {
        return $this->belongsTo(AutomobileModel::class, 'model_id');
    }

    public function color(): HasOne
    {
        return $this->HasOne(Color::class, 'id', 'color_id');
    }

    /**
     * Get the car's name.
     *
     * @return string
     */
    public function getCarNameAttribute(): string
    {
        return "{$this->model->brand->name} {$this->model->name}";
    }

    /**
     * The method deletes a previously uploaded photo
     *
     */
    public function deleteImage(): bool
    {
        if (Storage::disk('public')->exists($this->photo)){
            return Storage::disk('public')->delete($this->photo);
        }
        return true;
    }

}

app/Models/AutomobileModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class AutomobileModel extends Model
{
    use HasFactory;

    public $timestamps = false;

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 10;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'brand_id'
    ];

    public function brand(): BelongsTo
    {
        return $this->belongsTo(Brand::class, 'brand_id');
    }

    /**
     * Get the models's name.
     *
     * @return string
     */
    public function getFullModelNameAttribute(): string
    {
        return "{$this->brand->name} {$this->name}";
    }
}

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;

    public $timestamps = false;

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 10;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
    ];
}

app/Models/Color.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    use HasFactory;

    public $timestamps = false;

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 10;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
    ];
}

app/Models/Transmission.php
<?php

namespace App\Models;

class Transmission
{
    /**
     * @var array
     */
    private const TRANSMISSION_LIST = [
        'Automatic transmission',
        'Mechanical transmission',
        'CVT transmission',
        'Robotic transmission'
    ];

    /**
     * @return string[]
     */
    public static function getTransmissionType(): array
    {
        return self::TRANSMISSION_LIST;
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'user_type'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/admin/model/_form.blade.php
<div class="card card-default">
    <form action="{{ $route }}" method="POST" enctype="multipart/form-data">
        @csrf
        @if($method)
        @method($method)
        @endif
        <div class="card-body">
            <div class="form-group">
                <label for="brand_id">Brand name</label>
                <select class="custom-select form-control-border" id="brand_id" name="brand_id" autocomplete="off">
                    <option value="0">
                        Select brand name
                    </option>
                    @foreach($data['brands'] AS $brand)
                        <option value="{{ $brand->id }}"
                            @if($data['model'])
                                {{ ($brand->id == $data['model']->brand_id) ? 'selected=selected' : '' }}
                            @else
                                {{ ($brand->id == old('brand_id')) ? 'selected=selected' : '' }}
                            @endif
                            >
                            {{ $brand->name }}
                        </option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="name">Model name</label>
                <input type="text" class="form-control" id="name" name="name" value="{{ $data['model']->name ?? old('name') }}"
                       placeholder="Enter model name"/>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>
</div>

resources/views/admin/model/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        @include('admin.includes.headerWithBreadcrumbs', [
            'route' => route('brand.index'),
            'title' => $title,
            'pageName' => $pageName ?? null
        ])
    </section>
    <section class="content">
        @if ($errors->any())
            @include('admin.includes.errors', ['errors' => $errors])
        @endif

        @include('admin/model/_form', [
            'route' => route('model.store'),
            'method' => null,
            'errors' => $errors,
            'data' => $data
        ])

    </section>
@endsection

resources/views/admin/model/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        @include('admin.includes.headerWithBreadcrumbs', [
            'route' => route('model.index'),
            'title' => $title,
            'pageName' => $pageName ?? null
        ])
    </section>
    <section class="content">
        @if ($errors->any())
            @include('admin.includes.errors', ['errors' => $errors])
        @endif

        @include('admin/model/_form', [
            'route' => route('model.update', $data['model']->id),
            'method' => 'PUT',
            'errors' => $errors,
            'data' => $data
        ])
    </section>
@endsection

resources/views/admin/model/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        @include('admin.includes.headerWithBreadcrumbs', [
            'route' => route('model.index'),
            'title' => $title,
            'pageName' => $pageName ?? null
        ])
    </section>

    <section class="content">
        @if(session()->has('success'))
            @include('admin.includes.success')
        @endif
        <div class="card">
            <div class="card-header">
                <a class="btn btn-success btn-sm mw-100" href="{{ route('model.create') }}">
                    <i class="far fa-plus-square"></i>
                </a>
                <div class="card-tools">
                    {{ $models->links() }}
                </div>
            </div>
            @if ($models->isNotEmpty())
            <div class="card-body p-0" style="display: block;">
                <table class="table table-striped projects">
                    <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th style="width: 40%">
                            Model Name
                        </th>
                        <th style="width: 40%">
                            Brand Name
                        </th>
                        <th style="width: 20%">
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($models AS $model)
                    <tr>
                        <td>
                            {{ $model->id }}
                        </td>
                        <td>
                            <a href="{{ route('model.show', $model->id) }}">
                                {{ $model->name }}
                            </a>
                            <br>
                        </td>
                        <td>
                            <a href="{{ route('brand.show', $model->brand->id) }}">
                                {{ $model->brand->name }}
                            </a>
                        </td>
                        <td class="project-actions text-right">
                            <div class="btn-group">
                                <a class="btn btn-outline-primary btn-sm" href="{{ route('model.edit', $model->id) }}">
                                    <i class="fas fa-pencil-alt pt-2 pl-1 pr-1"></i>
                                </a>
                                <a type="button" class="btn btn-outline-danger delete-trigger" data-toggle="modal"
                                        data-target="#modal_delete"
                                        data-delete-url="{{ route('model.destroy', $model->id) }}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            @else
                <div class="card-body" style="display: block;">
                    <div class="col-12">
                        <h5>{{ __('messages.models.noDataFound') }}</h5>
                    </div>
                </div>
            @endif
            <div class="card-footer clearfix">
                {{ $models->links() }}
            </div>
        </div>
    </section>
    @include('admin.includes.delete-modal',[
            'message' => __('messages.models.onDeleteRecord')
        ])
@endsection

resources/views/admin/model/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        @include('admin.includes.headerWithBreadcrumbs', [
            'route' => route('model.index'),
            'title' => $title,
            'pageName' => $pageName ?? null
        ])
    </section>
    <section class="content">
        <div class="card">
            <div class="card-header">
                <a class="btn btn-success btn-sm mw-100" href="{{ route('model.edit', $model->id) }}">
                    <i class="fas fa-pencil-alt"></i>
                </a>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Brand name</label>
                    <h3>{{ $model->brand->name }}</h3>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Model name</label>
                    <h3>{{ $model->name }}</h3>
                </div>
            </div>
        </div>

    </section>
@endsection