routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::middleware(['auth', 'isAdmin'])->group(function () {
    Route::get('/admin', [App\Http\Controllers\HomeController::class, 'index'])->name('adminHome');
    Route::resource('/admin/brand', 'App\Http\Controllers\BrandController');
    Route::resource('/admin/model', 'App\Http\Controllers\AutomobileModelController');
    Route::resource('/admin/car', 'App\Http\Controllers\AutomobileController');
    Route::resource('/admin/color', 'App\Http\Controllers\ColorController');
});

Auth::routes();

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ config('app.name') }}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link href="{{ mix('css/app.css') }}" rel="stylesheet">

    @yield('third_party_stylesheets')
    @stack('page_css')
</head>

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown user-menu">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                    <img src="{{ asset('/images/user2-160x160.jpg') }}"
                         class="user-image img-circle elevation-2" alt="User Image">
                    <span class="d-none d-md-inline">{{ Auth::user()->name }}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <li class="user-header bg-primary">
                        <img src="{{ asset('/images/user2-160x160.jpg') }}"
                             class="img-circle elevation-2"
                             alt="User Image">
                        <p>
                            {{ Auth::user()->name }}
                            <small>Member since {{ Auth::user()->created_at->format('M. Y') }}</small>
                        </p>
                    </li>
                    <li class="user-footer">
                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                        <a href="#" class="btn btn-default btn-flat float-right"
                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            Sign out
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>

    @include('layouts.sidebar')

    <div class="content-wrapper">
        @yield('content')
    </div>

    <footer class="main-footer">
        <div class="float-right d-none d-sm-block">
            <b>Version</b> 3.1.0
        </div>
        <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights
        reserved.
    </footer>
</div>
<script src="{{ mix('js/app.js') }}"></script>
<script src="{{ asset('js/toastr.min.js') }}"></script>

@yield('third_party_scripts')
@stack('page_scripts')
</body>
</html>

resources/views/layouts/menu.blade.php
<!-- need to remove -->
<li class="nav-item">
    <a href="{{ route('adminHome') }}" class="nav-link {{ (request()->is('admin')) ? 'active' : '' }}">
        <i class="nav-icon fas fa-home"></i>
        <p>Home</p>
    </a>
</li>

<li class="nav-header">{{ \Illuminate\Support\Str::upper('Catalog') }}</li>
<li class="nav-item">
    <a href="{{ route('car.index') }}" class="nav-link {{ (request()->is('admin/car*')) ? 'active' : '' }}">
        <i class="nav-icon fas fa-car"></i>
        <p>Automobile</p>
    </a>
</li>

<li class="nav-header">{{ \Illuminate\Support\Str::upper('Reference Book') }}</li>
<li class="nav-item">
    <a href="{{ route('brand.index') }}" class="nav-link {{ (request()->is('admin/brand*')) ? 'active' : '' }}">
        <i class="nav-icon fas fa-city"></i>
        <p>Brand</p>
    </a>
</li>
<li class="nav-item">
    <a href="{{ route('model.index') }}" class="nav-link {{ (request()->is('admin/model*')) ? 'active' : '' }}">
        <i class="nav-icon fas fa-trademark"></i>
        <p>Model</p>
    </a>
</li>
<li class="nav-item">
    <a href="{{ route('color.index') }}" class="nav-link {{ (request()->is('admin/color*')) ? 'active' : '' }}">
        <i class="nav-icon fas fa-paint-brush"></i>
        <p>Colors</p>
    </a>
</li>

<li class="nav-header"><hr class="btn-default mt-1 mb-1"/></li>

<li class="nav-item">
    <a href="#" class="nav-link"
       onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
        <i class="nav-icon fas fa-door-open"></i>
        <p>Sign out</p>
    </a>
    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
        @csrf
    </form>
</li>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="{{ route('home') }}" class="brand-link">
        <img src="{{ asset('/images/AdminLTELogo.png') }}"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3">
        <span class="brand-text font-weight-light">{{ config('app.name') }}</span>
    </a>

    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                @include('layouts.menu')
            </ul>
        </nav>
    </div>

</aside>