routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::middleware(['auth', 'isAdmin'])->group(function () {
    Route::get('/admin', [App\Http\Controllers\HomeController::class, 'index'])->name('adminHome');
    Route::resource('/admin/brand', 'App\Http\Controllers\BrandController');
    Route::resource('/admin/model', 'App\Http\Controllers\AutomobileModelController');
    Route::resource('/admin/car', 'App\Http\Controllers\AutomobileController');
    Route::resource('/admin/color', 'App\Http\Controllers\ColorController');
});

Auth::routes();

app/Models/Color.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    use HasFactory;

    public $timestamps = false;

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 10;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
    ];
}

app/Http/Controllers/ColorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreColorRequest;
use App\Http\Requests\UpdateColorRequest;
use App\Models\Automobile;
use App\Models\Color;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Database\QueryException;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;

class ColorController extends Controller
{
    private $title = "Colors";

    private $pageName = "";

    /**
     * Display a listing of the resource.
     *
     * @return Renderable
     */
    public function index(): Renderable
    {
        return view('admin/color/index', [
            'title' => $this->title,
            'colors' => Color::paginate()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Renderable
     */
    public function create(): Renderable
    {
        $this->pageName = "Create color";

        return view('admin.color.create', [
            'title' => $this->title,
            'pageName' => $this->pageName,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreColorRequest $request
     * @return RedirectResponse
     */
    public function store(StoreColorRequest $request): RedirectResponse
    {
        try {
            Color::create($request->all());
        } catch (QueryException $error) {
            return redirect()->back()
                ->withErrors(['error' => $error->getMessage()])
                ->withInput($request->input());
        }

        return redirect()->route('color.index')->with('success','Color created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param Color $color
     * @return Renderable
     */
    public function show(Color $color): Renderable
    {
        $this->pageName = "View color \"" . $color->name . "\"";

        return view('admin.color.show', [
            'title' => $this->title,
            'pageName' => $this->pageName,
            'color' => $color
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Color $color
     * @return Renderable
     */
    public function edit(Color $color): Renderable
    {
        $this->pageName = "Edit brand \"" . $color->name . "\"";

        return view('admin.color.edit', [
            'title' => $this->title,
            'pageName' => $this->pageName,
            'color' => $color
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateColorRequest $request
     * @param Color $color
     * @return RedirectResponse
     */
    public function update(UpdateColorRequest $request, Color $color): RedirectResponse
    {
        try {
            $color->update($request->all());
        } catch (QueryException $error) {
            return redirect()->back()
                ->withErrors(['error' => $error->getMessage()])
                ->withInput($request->input());
        }

        return redirect()->route('color.index')->with('success','Color updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Color $color
     * @return RedirectResponse
     */
    public function destroy(Color $color): RedirectResponse
    {
        try {
            $color->delete();
        } catch (QueryException $error) {
            return redirect()->back()
                ->withErrors(['error' => $error->getMessage()]);
        }

        return redirect()->route('color.index')
            ->with('success','Color deleted successfully.');
    }
}

resources/views/admin/color/_form.blade.php
<div class="card card-default">
    <form action="{{ $route }}" method="POST" enctype="multipart/form-data">
        @csrf
        @if($method)
        @method($method)
        @endif
        <div class="card-body">
            <div class="form-group">
                <label for="name">Color name</label>
                <input type="text" class="form-control" id="name" name="name" value="{{ $data->name ?? old('name') }}"
                       placeholder="Enter color name"/>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>
</div>

resources/views/admin/color/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        @include('admin.includes.headerWithBreadcrumbs', [
            'route' => route('brand.index'),
            'title' => $title,
            'pageName' => $pageName ?? null
        ])
    </section>
    <section class="content">
        @if ($errors->any())
            @include('admin.includes.errors', ['errors' => $errors])
        @endif

        @include('admin/color/_form', [
            'route' => route('color.store'),
            'method' => null,
            'data' => null
        ])

    </section>
@endsection

resources/views/admin/color/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        @include('admin.includes.headerWithBreadcrumbs', [
            'route' => route('color.index'),
            'title' => $title,
            'pageName' => $pageName ?? null
        ])
    </section>
    <section class="content">
        @if ($errors->any())
            @include('admin.includes.errors', ['errors' => $errors])
        @endif

        @include('admin/brand/_form', [
            'route' => route('color.update', $color->id),
            'method' => 'PUT',
            'data' => $color
        ])
    </section>
@endsection

resources/views/admin/color/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        @include('admin.includes.headerWithBreadcrumbs', [
            'route' => route('color.index'),
            'title' => $title,
            'pageName' => $pageName ?? null
        ])
    </section>
    <section class="content">
        @if(session()->has('success'))
            @include('admin.includes.success')
        @endif
        @if ($errors->any())
            @include('admin.includes.errors', ['errors' => $errors])
        @endif
        <div class="card">
            <div class="card-header">
                <a class="btn btn-success btn-sm mw-100" href="{{ route('color.create') }}">
                    <i class="far fa-plus-square"></i>
                </a>
                <div class="card-tools">
                    {{ $colors->links() }}
                </div>
            </div>
            @if ($colors->isNotEmpty())
            <div class="card-body p-0" style="display: block;">
                <table class="table table-striped projects">
                    <thead>
                    <tr>
                        <th style="width: 1%">#</th>
                        <th style="width: 40%">Color Name</th>
                        <th style="width: 20%">{{-- --}}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($colors AS $color)
                    <tr>
                        <td>
                            {{ $color->id }}
                        </td>
                        <td>
                            <a href="{{ route('color.show', $color->id) }}">
                                {{ $color->name }}
                            </a>
                        </td>
                        <td class="project-actions text-right">
                            <div class="btn-group">
                                <a class="btn btn-outline-primary btn-sm" href="{{ route('color.edit', $color->id) }}">
                                    <i class="fas fa-pencil-alt pt-2 pl-1 pr-1"></i>
                                </a>
                                <a type="button" class="btn btn-outline-danger delete-trigger" data-toggle="modal"
                                        data-target="#modal_delete"
                                        data-delete-url="{{ route('color.destroy', $color->id) }}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            @else
                <div class="card-body" style="display: block;">
                    <div class="col-12">
                        <h5>{{ __('messages.colors.noDataFound') }}</h5>
                    </div>
                </div>
            @endif

            <!-- /.card-body -->
            <div class="card-footer clearfix">
                {{ $colors->links() }}
            </div>
        </div>
    </section>
    @include('admin.includes.delete-modal',[
            'message' => __('messages.colors.onDeleteRecord')
        ])
@endsection

resources/views/admin/color/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        @include('admin.includes.headerWithBreadcrumbs', [
            'route' => route('color.index'),
            'title' => $title,
            'pageName' => $pageName ?? null
        ])
    </section>
    <section class="content">
        <div class="card">
            <div class="card-header">
                <a class="btn btn-success btn-sm mw-100" href="{{ route('color.edit', $color->id) }}">
                    <i class="fas fa-pencil-alt"></i>
                </a>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label>Brand name</label>
                    <h3>{{ $color->name }}</h3>
                </div>
            </div>
        </div>
    </section>
@endsection